### ISSUE TITLE
correct_time has many issues

### ISSUE THREAD

**Issue by SWotherspoon** [SESman/rbl#1]
The cirrect_time has a number of problems.  Most notably, it seems to assume the correct sampling frequency is the most common frequency, which may not be the case.

The method for inserting the missing times also seems overly complicated and often fails.  For example, duplicating the first row several times causes the function to fail.

> exses$tdr <- correct_time(exses$tdr[c(1,1,1,2:nrow(exses$tdr)),], verbose = FALSE)
> Sampling frequency: 1 Hz. 
>  Error in matrix(nrow = length(miss_area) - 1, ncol = ncol(obj)) : 
>   invalid 'nrow' value (< 0) In addition: Warning message:
> In correct_time(exses$tdr[c(1, 1, 1, 2:nrow(exses$tdr)), ], verbose = FALSE) :
>   Missing time stamp(s). -1 rows added.

If I get time I will put together a replacement, but I am unsure how to best choose the sampling frequency.  What is wrong with choosing the shortest non-zero observed time?

**Comment by SWotherspoon** [comment]
First attempt at a suggested replacement.  This has the advantage of separating the removal of duplicates and filling in hte missing times. The ave function is slow so this is still quite slow if there are many many duplicate rows.   

```
correct_duplicated <- function(obj, time_seq = 1, verbose = FALSE) {
  ## Check time specification
  if(!(length(time_seq)==1) && is.POSIXct(obj[,time_seq]))
    stop("time_seq must specify a column of POSIXct times")

  ## Round times to nearest second
  obj[,time_seq] <- .POSIXct(round(as.numeric(obj[,time_seq])),tz="UTC")

  dup <- duplicated(obj[,time_seq])
  if(any(dup)) {
    ## Extract any row that is duplicated
    rs <- which(obj[,time_seq] %in% obj[dup,time_seq])
    obj.dup <- obj[rs,]
    ## Average the non-time columns
    for(k in setdiff(seq_along(obj.dup),time_seq)) {
      if(is.numeric(obj.dup[,k]))
        obj.dup[,k] <- ave(obj.dup[,k],obj.dup[,time_seq])
      else if(is.logical(obj.dup[,k]))
        obj.dup[,k] <- ave(obj.dup[,k],obj.dup[,time_seq],FUN=any)
      else 
        warning("Duplicate non numeric data")
    }
    ## Replace in original then remove duplicated
    obj[rs,] <- obj.dup
    obj <- obj[!dup,]
  }
  invisible(obj)
}

correct_timeA <- function(obj, time_seq = 1, verbose = FALSE) {

  gcd <- function(a,b) if(b==0) a else gcd(b,a%%b)

  ## Check time specification
  if(!(length(time_seq)==1) && is.POSIXct(obj[,time_seq]))
    stop("time_seq must specify a column of POSIXct times")

  ## Round times to nearest second
  obj[,time_seq] <- .POSIXct(round(as.numeric(obj[,time_seq])),tz="UTC")

  ## Remove duplicate times 
  if(anyDuplicated(obj[,time_seq]))
    obj <- correct_duplicated(obj,time_seq,verbose)

  ## Assume sampling interval is greatest common divisor of observed intervals
  dt <- Reduce(gcd,unique(diff(sort(as.numeric(obj[,time_seq])))))

  ## Generate complete sequence of times, expand data and fill in missing times.
  tms <- seq(min(obj[,time_seq]),max(obj[,time_seq]),dt)
  obj <- obj[match(tms,obj[,time_seq]),]
  obj[,time_seq] <- tms
  invisible(obj)
}

data(exses)

## Basic tests
tst <- exses$tdr[1:10,]
(res <- correct_timeA(tst))
(res <- correct_timeA(tst[,ncol(tst):1],ncol(tst)))
(res <- correct_timeA(tst[nrow(tst):1,]))
(res <- correct_timeA(tst[sample.int(nrow(tst),2*nrow(tst),replace=TRUE),]))
(res <- correct_timeA(tst[sample.int(nrow(tst),nrow(tst)/2,replace=FALSE),]))

## Test for speed on larger data
tst <- exses$tdr
res <- correct_timeA(tst)
tst <- rbind(tst,tst[sample.int(nrow(tst),5000),])
res <- correct_timeA(tst)
```

**Comment by SESman** [comment]
You are right, using gcd to infer sampling frequency and splitting "duplicates" and "jumps" corrections into distinct functions are good ideas. I have merged your patch, with minor changes (to handle character/factor data, keep original time zone attribute and print additional info with verbose option). I tested the new code with 10^6 rows with decent run time results (< 2 minutes) so I guess speed profiling can wait for real-world testing. Package version switched to 0.1.29.
Thank you for this feedback. PR are welcome anytime.

**Comment by SWotherspoon** [comment]
Thanks for the quick response.

In relation to carrying time zones forward - I strongly recommend that you do not encourage people to use timezones other than GMT or UTC.  In any local time that has any form of daylight savings or other adjustment, there are times that do not exist (eg in a timezone with daylight savings, when the local time jumps forward there is a hour that doesn't exist). When you convert the regular time sequence of times that the logger produces these impossible times get converted to NA.  Typically this happens in the middle of the recording period and the user doesn't immediately notice, and it just leads to all sorts of problems.

**Comment by SESman** [comment]
I not sure if I ever used other tz than UTC, I prefer to use a new column to store local time or local TZ when it is needed. So I don't see any problem in forcing tz to UTC. Now I remember why I assumed the correct sampling frequency was the most common one: non-integer sampling intervals. I think that it should work fine with the last update.
