### ISSUE TITLE
Error when trying example

### ISSUE THREAD

**Issue by rociojoo** [SESman/rbl#2]
I tried to run the codes in https://github.com/SESman/rbl, but when I run

library(rbl)
data(exses) # Load the package example dataset
ind(ses)    # Set it as default individual to avoid writing its name everytime

# Extract bottom of the dive number 65 of exses
dv_btt <- tdrply(identity, ty = "_", no = 65)

I get

Error in eval(cache$link$val, cache$link$env) : object 'ses' not found

I changed "ses" for "exses", which fixed the error. But then, when I execute

tdrply(max, "depth", ty = "!_/", no = 400, na.rm = TRUE)

I get

!_/#400
     NA
Warning message:
In FUN(X[[i]], ...) :
  Some periods have no matching entry in "delim" table of "obj". Found for "no" in  400

I restarted R, and made sure I have the updated version of the package.

Could you please tell me where the error could be coming from?

**Comment by SESman** [comment]
Hello,

Thank you for your feedback, here is my answer:

```R
library(rbl)

data(exses) 
ind(exses)  # Instead of "ses" indeed...

tdrply(max, "depth", ty = "!_/", no = 400, na.rm = TRUE)
# !_/#400 
#   NA 
# Warning message:
#   In FUN(X[[i]], ...) :
#   Some periods have no matching entry in "delim" table of "obj". Found for "no" in  400

# This warning says that tdrply could not find dive/bottom delimitation information 
# for dive no  400.
# /!\ That would be because I downsized the example dataset "exses" (which is still > 40 MB !)

# Now the last dive in this dataset is actually : 
max(exses$delim$no_dive)
# 311

# NB: max(exses$no_dive) may be a easier way to get access to this info
# but is not recommended: its true purpose is to store the dive numbers to use
# by default (some dives may be systematically ignore if, for example, 
# their data are corrupted) when the "no" argument of "tdrply" is not specified...

tdrply(max, "depth", ty = "!_/", no = 311, na.rm = TRUE)
# !_/#311 
#   601.5 

# Which seems to work as expected. Now I need to fix the README file asap.
```

I wish you good luck with the rest package. I haven't used it myself for some time now.

**Comment by rociojoo** [comment]
Great, thanks for the quick reply!

**Comment by SESman** [comment]
You're welcome !
